filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/nodeapp
  version: 0.0.1
  name: nodeapp
templates: {}
renderedvalues: {}
