filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/nodeapp
  version: 0.0.1
  name: nodeapp
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
